name: PowerShell ScriptAnalyzer

on:
  push:
    paths:
      - '**.ps1'
      - '**.psm1'
  pull_request:

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Analyze PowerShell Scripts
        run: Invoke-ScriptAnalyzer -Path . -Recurse -Verbose
        shell: pwsh
